export const GET_DOCUMENT_TEXT = 'GET_DCOUMENT_TEXT';
export const UPDATE_SEARCH_INDEX = 'UPDATE_SEARCH_INDEX';
export const SET_SEARCH_INDEX = 'SET_SEARCH_INDEX';
export const SET_PAGE_TO_SEARCH_FROM = 'SET_PAGE_TO_SEARCH_FROM';
export const UPDATE_SEARCH_INDEX_PAGE_INDEX = 'UPDATE_SEARCH_INDEX_PAGE_INDEX';
export const UPDATE_SEARCH_RELATIVE_INDEX = 'UPDATE_SEARCH_RELATIVE_INDEX';
export const UPDATE_SEARCH_TERM = 'UPDATE_SEARCH_TERM';
export const SET_SEARCH_IS_LOADING = 'SET_SEARCH_IS_LOADING';
